import { ITable, KitchenOrder, TPaymentType } from "@/types/types";

//  cart demo data
export type TCartItem = {
    productId: string;
    variantId: string;
    titleEn: string;
    titleBn: string;
    variantNameEn: string;
    variantNameBn: string;
    price: number;
    quantity: number;
    productImage: string;
};

export const paymentMethods: TPaymentType[] = [
    { id: 1, provider: "cash", name: { en: "Cash", bn: "ক্যাশ" } },
    { id: 2, provider: "bkash", name: { en: "Bkash", bn: "বিকাশ" } },
    { id: 3, provider: "bank", name: { en: "Bank", bn: "ব্যাংক" } },
]


export const tableData: ITable[] = [
    { id: 1, isBooked: true, tableNumber: 1 },
    { id: 2, isBooked: false, tableNumber: 2 },
    { id: 3, isBooked: false, tableNumber: 3 },
    { id: 4, isBooked: true, tableNumber: 4 },
    { id: 5, isBooked: false, tableNumber: 5 },
    { id: 6, isBooked: false, tableNumber: 6 },
    { id: 7, isBooked: true, tableNumber: 7 },
    { id: 8, isBooked: true, tableNumber: 8 },
    { id: 9, isBooked: false, tableNumber: 9 },
]


export const kitchenOrders: KitchenOrder[] = [
    {
        id: 233,
        waiter: { id: 1, name: "Akash" },
        orderFor: "Dine-In",
        tableId: 2,
        items: [
            {
                "img": "dashboard/images/products/1768561033.jpg",
                "title": "কাঁকড়া মাসালা / Kakra Masala",
                "discount": 0,
                "id": 48,
                "quantity": 1,
                "status": "pending",
                "variation": "1 পিস ছোট",
                "price": 250
            },
            {
                "quantity": 1,
                "img": "dashboard/images/products/1768562267.jpg",
                "title": "চিকেন বিরিয়ানি / Chicken Beriany",
                "discount": 0,
                "id": 44,
                "status": "pending",
                "variation": "1:01",
                "price": 220
            },
            {
                "quantity": 1,
                "img": "dashboard/images/products/1768499606.jpg",
                "title": "এগ্‌ চাউমিন / Egg Chawmin",
                "discount": 0,
                "id": 110,
                "status": "pending",
                "variation": "1:01",
                "price": 130
            },
            {
                "quantity": 1,
                "img": "",
                "title": "সেট মিল-১ / Set Mill-1",
                "discount": 0,
                "id": 1,
                "status": "pending",
                "variation": "1:1",
                "price": 180
            },
            {
                "quantity": 1,
                "img": "dashboard/images/products/1768560988.jpg",
                "title": "অক্টোপাস / Octopas",
                "discount": 0,
                "id": 54,
                "status": "pending",
                "variation": "Grilled",
                "price": 590
            },
            {
                "quantity": 1,
                "img": "dashboard/images/products/1768500200.jpg",
                "title": "মোমো / MoMo",
                "discount": 0,
                "id": 99,
                "status": "pending",
                "variation": "8 পিস ফ্রাই",
                "price": 320
            },
            {
                "quantity": 1,
                "img": "dashboard/images/products/1768561002.jpg",
                "title": "লবিস্টার মাসালা / Lobister",
                "discount": 0,
                "id": 52,
                "status": "pending",
                "variation": "1 পিস ছোট",
                "price": 880
            }
        ]
    },
    {
        id: 244,
        waiter: { id: 1, name: "Akash" },
        orderFor: "Online",
        tableId: null,
        items: [
            {
                "img": "dashboard/images/products/1768561033.jpg",
                "title": "কাঁকড়া মাসালা / Kakra Masala",
                "discount": 0,
                "id": 48,
                "quantity": 1,
                "status": "pending",
                "variation": "1 পিস ছোট",
                "price": 250
            },
            {
                "quantity": 1,
                "img": "dashboard/images/products/1768562267.jpg",
                "title": "চিকেন বিরিয়ানি / Chicken Beriany",
                "discount": 0,
                "id": 44,
                "status": "pending",
                "variation": "1:01",
                "price": 220
            },
            {
                "quantity": 1,
                "img": "dashboard/images/products/1768499606.jpg",
                "title": "এগ্‌ চাউমিন / Egg Chawmin",
                "discount": 0,
                "id": 110,
                "status": "pending",
                "variation": "1:01",
                "price": 130
            },
            {
                "quantity": 1,
                "img": "",
                "title": "সেট মিল-১ / Set Mill-1",
                "discount": 0,
                "id": 1,
                "status": "pending",
                "variation": "1:1",
                "price": 180
            },
            {
                "quantity": 1,
                "img": "dashboard/images/products/1768560988.jpg",
                "title": "অক্টোপাস / Octopas",
                "discount": 0,
                "id": 54,
                "status": "pending",
                "variation": "Grilled",
                "price": 590
            },
            {
                "quantity": 1,
                "img": "dashboard/images/products/1768500200.jpg",
                "title": "মোমো / MoMo",
                "discount": 0,
                "id": 99,
                "status": "pending",
                "variation": "8 পিস ফ্রাই",
                "price": 320
            },
            {
                "quantity": 1,
                "img": "dashboard/images/products/1768561002.jpg",
                "title": "লবিস্টার মাসালা / Lobister",
                "discount": 0,
                "id": 52,
                "status": "pending",
                "variation": "1 পিস ছোট",
                "price": 880
            }
        ]
    },
]


export const orders = [
    {
        "id": 1002,
        "customer_id": 47,
        "customer_type": "Dine-In",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-02-01",
        "delivery_date": "2026-02-01",
        "estimate_by": 1,
        "token_no": "4",
        "estimate_number": "# 00001003",
        "total": "0.00",
        "receivable": "170.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "0.00",
        "final_receivable": "170.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 2,
        "status": 2,
        "created_at": "2026-02-01T01:44:35.000000Z",
        "updated_at": "2026-02-01T04:24:54.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 2725,
                "estimate_id": 1002,
                "product_name": "শাহী ভুনা খিচুড়ি / Sahi Vuna Khacuri",
                "product_id": 36,
                "variation_id": 42,
                "rate": "170.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "170.00",
                "ordered_sub_total": "170.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-02-01T01:44:35.000000Z",
                "updated_at": "2026-02-01T01:44:35.000000Z",
                "product": {
                    "id": 36,
                    "name": "শাহী ভুনা খিচুড়ি / Sahi Vuna Khacuri",
                    "code": "36",
                    "category_id": 7,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "170.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768562285.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 43,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-30T06:10:40.000000Z"
                },
                "variation": {
                    "id": 42,
                    "product_id": 36,
                    "variation": "1:01",
                    "cost": "0.00",
                    "price": "170.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 1001,
        "customer_id": 47,
        "customer_type": "Online",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-02-01",
        "delivery_date": "2026-02-01",
        "estimate_by": 1,
        "token_no": "3",
        "estimate_number": "# 00001002",
        "total": "0.00",
        "receivable": "300.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "120.00",
        "final_receivable": "420.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 2,
        "status": 2,
        "created_at": "2026-02-01T01:26:42.000000Z",
        "updated_at": "2026-02-01T04:24:57.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 2724,
                "estimate_id": 1001,
                "product_name": "কেক / Cake",
                "product_id": 138,
                "variation_id": 182,
                "rate": "300.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "300.00",
                "ordered_sub_total": "300.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-02-01T01:26:42.000000Z",
                "updated_at": "2026-02-01T01:26:42.000000Z",
                "product": {
                    "id": 138,
                    "name": "কেক / Cake",
                    "code": "138",
                    "category_id": 22,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "300.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768493412.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 12,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-29T10:07:30.000000Z"
                },
                "variation": {
                    "id": 182,
                    "product_id": 138,
                    "variation": "0.5 Pound",
                    "cost": null,
                    "price": "300.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": "2026-01-02T12:24:52.000000Z",
                    "updated_at": "2026-01-02T12:24:52.000000Z"
                }
            }
        ]
    },
    {
        "id": 999,
        "customer_id": 47,
        "customer_type": "Online",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": 1,
        "estimate_date": "2026-02-01",
        "delivery_date": "2026-02-01",
        "estimate_by": 1,
        "token_no": "1",
        "estimate_number": "# 00001000",
        "total": "0.00",
        "receivable": "140.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "0.00",
        "final_receivable": "140.00",
        "delivery_by": 1,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 0,
        "is_online_app": 0,
        "status": 0,
        "created_at": "2026-02-01T01:24:27.000000Z",
        "updated_at": "2026-02-01T01:24:27.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 2722,
                "estimate_id": 999,
                "product_name": "চিকেন বার্গার  Chicken Burger",
                "product_id": 89,
                "variation_id": 122,
                "rate": "140.00",
                "main_unit_qty": 1,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "140.00",
                "ordered_sub_total": "140.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": 1,
                "is_prepared": 0,
                "created_at": "2026-02-01T01:24:27.000000Z",
                "updated_at": "2026-02-01T01:24:27.000000Z",
                "product": {
                    "id": 89,
                    "name": "চিকেন বার্গার / Chicken Burger",
                    "code": "89",
                    "category_id": 14,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "140.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768498711.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 153,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-29T15:26:00.000000Z"
                },
                "variation": {
                    "id": 122,
                    "product_id": 89,
                    "variation": "1 পিস",
                    "cost": "0.00",
                    "price": "140.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 801,
        "customer_id": 47,
        "customer_type": "Self Pickup",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-01-25",
        "delivery_date": "2026-01-25",
        "estimate_by": null,
        "token_no": "21",
        "estimate_number": "# 00000802",
        "total": "0.00",
        "receivable": "170.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "0.00",
        "final_receivable": "170.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 2,
        "status": 2,
        "created_at": "2026-01-25T08:49:52.000000Z",
        "updated_at": "2026-01-25T09:39:59.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 2189,
                "estimate_id": 801,
                "product_name": "চিকেন চাপ / Chicken Chap",
                "product_id": 107,
                "variation_id": 145,
                "rate": "170.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "170.00",
                "ordered_sub_total": "170.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-25T08:49:52.000000Z",
                "updated_at": "2026-01-25T08:49:52.000000Z",
                "product": {
                    "id": 107,
                    "name": "চিকেন চাপ / Chicken Chap",
                    "code": "107",
                    "category_id": 17,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "170.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768497140.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 116,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-31T15:02:07.000000Z"
                },
                "variation": {
                    "id": 145,
                    "product_id": 107,
                    "variation": "1 পিস",
                    "cost": "0.00",
                    "price": "170.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 800,
        "customer_id": 47,
        "customer_type": "Dine-In",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-01-25",
        "delivery_date": "2026-01-25",
        "estimate_by": null,
        "token_no": "20",
        "estimate_number": "# 00000801",
        "total": "0.00",
        "receivable": "250.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "0.00",
        "final_receivable": "250.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 2,
        "status": 2,
        "created_at": "2026-01-25T08:38:20.000000Z",
        "updated_at": "2026-01-25T09:40:03.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 2188,
                "estimate_id": 800,
                "product_name": "কাঁকড়া মাসালা / Kakra Masala",
                "product_id": 41,
                "variation_id": 48,
                "rate": "250.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "250.00",
                "ordered_sub_total": "250.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-25T08:38:20.000000Z",
                "updated_at": "2026-01-25T08:38:20.000000Z",
                "product": {
                    "id": 41,
                    "name": "কাঁকড়া মাসালা / Kakra Masala",
                    "code": "41",
                    "category_id": 8,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "250.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768561033.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 348,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-31T15:13:17.000000Z"
                },
                "variation": {
                    "id": 48,
                    "product_id": 41,
                    "variation": "1 পিস ছোট",
                    "cost": "0.00",
                    "price": "250.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 799,
        "customer_id": 47,
        "customer_type": "Take Way",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-01-25",
        "delivery_date": "2026-01-25",
        "estimate_by": null,
        "token_no": "19",
        "estimate_number": "# 00000800",
        "total": "0.00",
        "receivable": "250.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "120.00",
        "final_receivable": "370.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 2,
        "status": 2,
        "created_at": "2026-01-25T08:38:15.000000Z",
        "updated_at": "2026-01-25T09:40:07.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 2187,
                "estimate_id": 799,
                "product_name": "কাঁকড়া মাসালা / Kakra Masala",
                "product_id": 41,
                "variation_id": 48,
                "rate": "250.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "250.00",
                "ordered_sub_total": "250.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-25T08:38:15.000000Z",
                "updated_at": "2026-01-25T08:38:15.000000Z",
                "product": {
                    "id": 41,
                    "name": "কাঁকড়া মাসালা / Kakra Masala",
                    "code": "41",
                    "category_id": 8,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "250.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768561033.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 348,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-31T15:13:17.000000Z"
                },
                "variation": {
                    "id": 48,
                    "product_id": 41,
                    "variation": "1 পিস ছোট",
                    "cost": "0.00",
                    "price": "250.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 798,
        "customer_id": 47,
        "customer_type": "Online",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-01-25",
        "delivery_date": "2026-01-25",
        "estimate_by": null,
        "token_no": "18",
        "estimate_number": "# 00000799",
        "total": "0.00",
        "receivable": "250.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "120.00",
        "final_receivable": "370.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 2,
        "status": 2,
        "created_at": "2026-01-25T08:38:06.000000Z",
        "updated_at": "2026-01-25T09:14:47.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 2186,
                "estimate_id": 798,
                "product_name": "কাঁকড়া মাসালা / Kakra Masala",
                "product_id": 41,
                "variation_id": 48,
                "rate": "250.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "250.00",
                "ordered_sub_total": "250.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-25T08:38:06.000000Z",
                "updated_at": "2026-01-25T08:38:06.000000Z",
                "product": {
                    "id": 41,
                    "name": "কাঁকড়া মাসালা / Kakra Masala",
                    "code": "41",
                    "category_id": 8,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "250.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768561033.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 348,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-31T15:13:17.000000Z"
                },
                "variation": {
                    "id": 48,
                    "product_id": 41,
                    "variation": "1 পিস ছোট",
                    "cost": "0.00",
                    "price": "250.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 580,
        "customer_id": 47,
        "customer_type": "Online",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-01-18",
        "delivery_date": "2026-01-18",
        "estimate_by": null,
        "token_no": "18",
        "estimate_number": "# 00000581",
        "total": "0.00",
        "receivable": "690.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "0.00",
        "final_receivable": "690.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 1,
        "status": 2,
        "created_at": "2026-01-18T11:45:36.000000Z",
        "updated_at": "2026-01-18T13:24:47.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 1592,
                "estimate_id": 580,
                "product_name": "চিংড়ি মালাইকারি / Chingri Malaicari",
                "product_id": 29,
                "variation_id": 35,
                "rate": "690.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "690.00",
                "ordered_sub_total": "690.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-18T11:45:36.000000Z",
                "updated_at": "2026-01-18T11:45:36.000000Z",
                "product": {
                    "id": 29,
                    "name": "চিংড়ি মালাইকারি / Chingri Malaicari",
                    "code": "29",
                    "category_id": 5,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "690.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768660234.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-17T14:30:34.000000Z"
                },
                "variation": {
                    "id": 35,
                    "product_id": 29,
                    "variation": "6 পিস",
                    "cost": "0.00",
                    "price": "690.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 579,
        "customer_id": 47,
        "customer_type": "Online",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-01-18",
        "delivery_date": "2026-01-18",
        "estimate_by": null,
        "token_no": "17",
        "estimate_number": "# 00000580",
        "total": "0.00",
        "receivable": "820.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "0.00",
        "final_receivable": "820.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 1,
        "status": 2,
        "created_at": "2026-01-18T11:43:58.000000Z",
        "updated_at": "2026-01-18T11:44:33.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 1590,
                "estimate_id": 579,
                "product_name": "Cake",
                "product_id": 138,
                "variation_id": 182,
                "rate": "300.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "300.00",
                "ordered_sub_total": "300.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-18T11:43:58.000000Z",
                "updated_at": "2026-01-18T11:43:58.000000Z",
                "product": {
                    "id": 138,
                    "name": "কেক / Cake",
                    "code": "138",
                    "category_id": 22,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "300.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768493412.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 12,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-29T10:07:30.000000Z"
                },
                "variation": {
                    "id": 182,
                    "product_id": 138,
                    "variation": "0.5 Pound",
                    "cost": null,
                    "price": "300.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": "2026-01-02T12:24:52.000000Z",
                    "updated_at": "2026-01-02T12:24:52.000000Z"
                }
            },
            {
                "id": 1591,
                "estimate_id": 579,
                "product_name": "চিকেন পিজ্জা / Chicken Pizza",
                "product_id": 96,
                "variation_id": 129,
                "rate": "520.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "520.00",
                "ordered_sub_total": "520.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-18T11:43:58.000000Z",
                "updated_at": "2026-01-18T11:43:58.000000Z",
                "product": {
                    "id": 96,
                    "name": "চিকেন পিজ্জা / Chicken Pizza",
                    "code": "96",
                    "category_id": 15,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "520.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768498078.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 28,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-31T13:40:13.000000Z"
                },
                "variation": {
                    "id": 129,
                    "product_id": 96,
                    "variation": "9 ইঞ্চি",
                    "cost": "0.00",
                    "price": "520.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 575,
        "customer_id": 47,
        "customer_type": "Online",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-01-18",
        "delivery_date": "2026-01-18",
        "estimate_by": null,
        "token_no": "13",
        "estimate_number": "# 00000576",
        "total": "0.00",
        "receivable": "250.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "0.00",
        "final_receivable": "250.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 1,
        "status": 2,
        "created_at": "2026-01-18T11:34:27.000000Z",
        "updated_at": "2026-01-18T11:35:30.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 1582,
                "estimate_id": 575,
                "product_name": "কাঁকড়া মাসালা / Kakra Masala",
                "product_id": 41,
                "variation_id": 48,
                "rate": "250.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "250.00",
                "ordered_sub_total": "250.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-18T11:34:27.000000Z",
                "updated_at": "2026-01-18T11:34:27.000000Z",
                "product": {
                    "id": 41,
                    "name": "কাঁকড়া মাসালা / Kakra Masala",
                    "code": "41",
                    "category_id": 8,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "250.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768561033.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 348,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-31T15:13:17.000000Z"
                },
                "variation": {
                    "id": 48,
                    "product_id": 41,
                    "variation": "1 পিস ছোট",
                    "cost": "0.00",
                    "price": "250.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 574,
        "customer_id": 47,
        "customer_type": "Online",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-01-18",
        "delivery_date": "2026-01-18",
        "estimate_by": null,
        "token_no": "12",
        "estimate_number": "# 00000575",
        "total": "0.00",
        "receivable": "880.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "120.00",
        "final_receivable": "1000.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 1,
        "status": 2,
        "created_at": "2026-01-18T11:27:08.000000Z",
        "updated_at": "2026-01-18T11:35:13.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 1581,
                "estimate_id": 574,
                "product_name": "লবিস্টার মাসালা / Lobister",
                "product_id": 43,
                "variation_id": 52,
                "rate": "880.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "880.00",
                "ordered_sub_total": "880.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-18T11:27:08.000000Z",
                "updated_at": "2026-01-18T11:27:08.000000Z",
                "product": {
                    "id": 43,
                    "name": "লবিস্টার মাসালা / Lobister",
                    "code": "43",
                    "category_id": 8,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "880.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768561002.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 4,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-23T15:18:35.000000Z"
                },
                "variation": {
                    "id": 52,
                    "product_id": 43,
                    "variation": "1 পিস ছোট",
                    "cost": "0.00",
                    "price": "880.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 573,
        "customer_id": 47,
        "customer_type": "Online",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-01-18",
        "delivery_date": "2026-01-18",
        "estimate_by": null,
        "token_no": "11",
        "estimate_number": "# 00000574",
        "total": "0.00",
        "receivable": "170.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "120.00",
        "final_receivable": "290.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 1,
        "status": 1,
        "created_at": "2026-01-18T11:13:20.000000Z",
        "updated_at": "2026-01-18T11:14:13.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 1577,
                "estimate_id": 573,
                "product_name": "চিকেন চাপ / Chicken Chap",
                "product_id": 107,
                "variation_id": 145,
                "rate": "170.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "170.00",
                "ordered_sub_total": "170.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-18T11:13:20.000000Z",
                "updated_at": "2026-01-18T11:13:20.000000Z",
                "product": {
                    "id": 107,
                    "name": "চিকেন চাপ / Chicken Chap",
                    "code": "107",
                    "category_id": 17,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "170.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768497140.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 116,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-31T15:02:07.000000Z"
                },
                "variation": {
                    "id": 145,
                    "product_id": 107,
                    "variation": "1 পিস",
                    "cost": "0.00",
                    "price": "170.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": null,
                    "updated_at": null
                }
            }
        ]
    },
    {
        "id": 569,
        "customer_id": 47,
        "customer_type": "Online",
        "brand_id": 1,
        "waiter_id": 1,
        "table_id": null,
        "estimate_date": "2026-01-18",
        "delivery_date": "2026-01-18",
        "estimate_by": null,
        "token_no": "7",
        "estimate_number": "# 00000570",
        "total": "0.00",
        "receivable": "300.00",
        "discount": "0",
        "actual_discount": "0.00",
        "delivery_charge": "120.00",
        "final_receivable": "420.00",
        "delivery_by": null,
        "note": null,
        "convert_status": 0,
        "is_approved": 0,
        "is_due_print": 0,
        "update_count": 0,
        "order_status": "First Order",
        "created_by": null,
        "is_web": 1,
        "is_online_app": 1,
        "status": 2,
        "created_at": "2026-01-18T10:41:19.000000Z",
        "updated_at": "2026-01-18T10:41:59.000000Z",
        "customer": {
            "id": 47,
            "name": "Tahazzat Ali",
            "phone": "01777524051",
            "shop_name": null,
            "shop_name_bangla": null,
            "address_id": 13,
            "sr_id": null,
            "business_cat_id": null,
            "opening_receivable": "0.00",
            "opening_payable": "0.00",
            "wallet_balance": "0.00",
            "total_receivable": "0.00",
            "total_payable": "0.00",
            "note": "Goga Bazar",
            "created_at": "2026-01-18T10:41:19.000000Z",
            "updated_at": "2026-01-18T10:41:19.000000Z"
        },
        "items": [
            {
                "id": 1565,
                "estimate_id": 569,
                "product_name": "Cake",
                "product_id": 138,
                "variation_id": 182,
                "rate": "300.00",
                "main_unit_qty": 0,
                "sub_unit_qty": 0,
                "ordered_qty": 0,
                "returned": 0,
                "returned_sub_unit": 0,
                "returned_qty": 0,
                "returned_value": "0.000",
                "damage": 0,
                "damaged_value": 0,
                "discount_return": 0,
                "qty": 1,
                "discount_qty": 0,
                "sub_total": "300.00",
                "ordered_sub_total": "300.00",
                "order_status": "First Order",
                "is_edit": 0,
                "created_by": null,
                "is_prepared": 0,
                "created_at": "2026-01-18T10:41:19.000000Z",
                "updated_at": "2026-01-18T10:41:19.000000Z",
                "product": {
                    "id": 138,
                    "name": "কেক / Cake",
                    "code": "138",
                    "category_id": 22,
                    "brand_id": 1,
                    "cost": "0.00",
                    "price": "300.00",
                    "damage_price": "0.00",
                    "details": null,
                    "image": "dashboard/images/products/1768493412.jpg",
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 12,
                    "price_editable": 0,
                    "ecom_visible": 1,
                    "pos_visible": 1,
                    "stock_count": 0,
                    "stock_visible": 0,
                    "stock_visible_ecom": 0,
                    "description": null,
                    "status": 1,
                    "main_unit_id": 1,
                    "sub_unit_id": null,
                    "created_at": null,
                    "updated_at": "2026-01-29T10:07:30.000000Z"
                },
                "variation": {
                    "id": 182,
                    "product_id": 138,
                    "variation": "0.5 Pound",
                    "cost": null,
                    "price": "300.00",
                    "image": null,
                    "stock": 0,
                    "main_unit_stock": 0,
                    "sub_unit_stock": 0,
                    "total_sold": 0,
                    "created_at": "2026-01-02T12:24:52.000000Z",
                    "updated_at": "2026-01-02T12:24:52.000000Z"
                }
            }
        ]
    }
]